/* lwIP options for the host test: the values that matter match the C3 build
 * (ESP-IDF 6.1 defaults as in its sdkconfig.h / port lwipopts.h). */
#pragma once
#define NO_SYS                      0
#define SYS_LIGHTWEIGHT_PROT        1
#define LWIP_SOCKET                 1
#define LWIP_NETCONN                1
#define LWIP_NETIF_API              1
#define LWIP_COMPAT_SOCKETS         1
#define LWIP_POSIX_SOCKETS_IO_NAMES 1
#define LWIP_SOCKET_SELECT          1
#define LWIP_NETCONN_FULLDUPLEX     1
#define LWIP_NETCONN_SEM_PER_THREAD 1
#define LWIP_TCPIP_CORE_LOCKING     0
#define LWIP_IPV4                   1
#define LWIP_IPV6                   0
#define LWIP_ARP                    1
#define LWIP_ETHERNET               1
#define LWIP_DHCP                   0
#define LWIP_ICMP                   1
#define LWIP_UDP                    1
#define LWIP_TCP                    1
#define LWIP_TCP_KEEPALIVE          1
#define LWIP_SO_RCVTIMEO            1
#define LWIP_SO_SNDTIMEO            1
#define LWIP_SO_LINGER              TEST_SO_LINGER
#define SO_REUSE                    1
#define MEM_LIBC_MALLOC             1
#define MEMP_MEM_MALLOC             1
#define MEM_ALIGNMENT               4
#define MEMP_NUM_NETCONN            10
#define TCP_MSS                     1440
#define TCP_SND_BUF                 5760
#define TCP_WND                     5760
#define TCP_MAXRTX                  12
#define TCP_SYNMAXRTX               12
#define TCP_QUEUE_OOSEQ             1
#define TCP_TMR_INTERVAL            250
#define TCP_FIN_WAIT_TIMEOUT        20000
#define LWIP_TCP_RTO_TIME           1500
#define TCP_OVERSIZE                TCP_MSS
#define DEFAULT_TCP_RECVMBOX_SIZE   6
#define DEFAULT_ACCEPTMBOX_SIZE     6
#define DEFAULT_UDP_RECVMBOX_SIZE   6
#define TCPIP_MBOX_SIZE             32
#define DEFAULT_THREAD_STACKSIZE    16384
#define TCPIP_THREAD_STACKSIZE      16384
#define LWIP_TIMEVAL_PRIVATE        0
#define LWIP_ERRNO_STDINCLUDE       1
#define LWIP_STATS                  0
#define LWIP_DEBUG                  0
#define ESP_LWIP                    1
