#!/usr/bin/env python3
"""Generates wt32/main/font6x10.c from the misc-fixed 6x10 BDF font
(public domain: "Public domain terminal emulator font. Share and enjoy.").

    curl -LO https://raw.githubusercontent.com/olikraus/u8g2/master/tools/font/bdf/6x10.bdf
    python3 gen_font.py 6x10.bdf > ../main/font6x10.c

Only the characters the display needs: ASCII, Cyrillic (Ukrainian included)
and a few punctuation marks. Each glyph is 10 rows of 6 pixels, one byte per
row, bit 7 = leftmost pixel.
"""
import re
import sys

W, H = 6, 10
EXTRA = [0x00AB, 0x00B0, 0x00B7, 0x00BB, 0x02BC, 0x0490, 0x0491, 0x2013, 0x2014,
         0x2019, 0x2022, 0x2026, 0x2190, 0x2192]
WANT = set(range(0x20, 0x7F)) | set(range(0x400, 0x460)) | set(EXTRA)


def parse(text):
    ascent = descent = None
    for line in text.splitlines():
        if line.startswith('FONT_ASCENT'):
            ascent = int(line.split()[1])
        elif line.startswith('FONT_DESCENT'):
            descent = int(line.split()[1])
    assert ascent + descent == H, (ascent, descent)
    glyphs = {}
    for block in re.findall(r'STARTCHAR.*?ENDCHAR', text, re.S):
        cp = int(re.search(r'ENCODING (-?\d+)', block).group(1))
        if cp not in WANT:
            continue
        w, h, xo, yo = map(int, re.search(r'BBX (-?\d+) (-?\d+) (-?\d+) (-?\d+)', block).group(1, 2, 3, 4))
        bits = block.split('BITMAP')[1].split('ENDCHAR')[0].split()
        rows = [0] * H
        top = ascent - (yo + h)                 # cell row of the glyph's first bitmap row
        for i, hexrow in enumerate(bits):
            y = top + i
            if not 0 <= y < H:
                continue
            v = int(hexrow[:2], 16) >> max(0, xo)           # rows are byte-padded; W <= 8
            rows[y] = v & ((0xFF << (8 - W)) & 0xFF)
        glyphs[cp] = rows
    return glyphs


def main():
    glyphs = parse(open(sys.argv[1], encoding='latin-1').read())
    # all of ASCII, А-я, the Ukrainian letters and the extras must be there
    # (the font lacks a few rare Cyrillic letters such as U+0400)
    must = set(range(0x20, 0x7F)) | set(range(0x410, 0x450)) | {0x404, 0x406, 0x407, 0x454, 0x456, 0x457} | set(EXTRA)
    missing = sorted(must - set(glyphs))
    assert not missing, [hex(c) for c in missing]
    out = ['/* Generated by wt32/tools/gen_font.py from misc-fixed 6x10 (public domain). */',
           '#include "font6x10.h"', '',
           'const font_glyph_t font6x10[] = {']
    for cp in sorted(glyphs):
        out.append('    { 0x%04X, { %s } },' % (cp, ', '.join('0x%02X' % r for r in glyphs[cp])))
    out += ['};', '', 'const size_t font6x10_count = sizeof(font6x10) / sizeof(font6x10[0]);', '']
    print('\n'.join(out))


if __name__ == '__main__':
    main()
